os: linux
language: python
services: docker

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git 2> /dev/null

script:
  - './ci-util/build-docker.sh : :2017.1.0,latest &&
     ./fenics_desktop.py -d -n && docker stop $(docker ps -q) &&
     ./fenics_jupyter.py -d -n && docker stop $(docker ps -q) &&
     ./ci-util/trigger-via-api.sh'
